config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index 
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new 
    @article = Article.new
  end

  def create 
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params 
      params.require(:article).permit(:title, :author, :text)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article<h1>
<%= render "form" %>
<%= link_to "Back", articles_path %>

app/views/articles/index.html.erb
<%= stylesheet_link_tag "articles.css" %>
<section>
  <h1>The Big List of all Articles</h1>

  <div class="article_container">
    <% @articles.each do |article| %>

      <div class="article_headers">
        <h2 class="header_title"><%= article.title %></h1>
        <div class="header_info">
          <p class="header_date"><%= article.created_at %></p>
          <p class="header_divider"> | </p>
          <p class="header_user"><%= article.author %></p>
        </div>
      </div>

      <%= link_to image_tag("https://cdn.pixabay.com/photo/2015/09/09/16/05/forest-931706_960_720.jpg", :border => 0, :alt => '', :title => ''), article_path(article), :class => 'article_image' %>

      <div class="article_focus">
        <p class="text"><%= article.text %></p>
      </div>

      <div class="button_container">
        <%= link_to "Show", article_path(article), :class => "show_button" %>
        <%= link_to "Edit", edit_article_path(article), :class => "edit_button"  %>
        <%= link_to "Destroy", article_path(article), method: :delete, data: {confirm: "Are you sure?" }, :class => "destroy_button"  %>
      </div>
        
    <% end %>
  </div>
  
</section>

app/views/articles/new.html.erb
<h1>New Article<h1>
<%= render "form" %>

app/views/articles/show.html.erb
<h1>Show Page</h1>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Time:</strong>
  <%= @article.created_at %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog002</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>